### ISSUE TITLE
License Under GNU GPL v3.0

### ISSUE THREAD

**Issue by deavmi** [OpenStatus/OpenStatus-Client-Windows#2]
Make the project worth it.

**Comment by Walkman100** [comment]
@deavmi well? https://github.com/OpenStatus/OpenStatus-Client-Windows/issues/2#issuecomment-67640797

And:
> Cloning it to your account and removing it from this org and not saying that it is from or associated with DeavmiOSS.

Most of my other projects in my account have `DeavmiOSS` as the `AssemblyInfo` company, and install to a `DeavmiOSS` folder under `%ProgramFiles%`

**Comment by deavmi** [comment]
Well DeavmiOSS is still alive but now us a new entity. Called Crowbar. So
fresh beginnings. But DeavmiOSS is not attached to it
Renaming all projects with DeavmiOSS copyright to Crowbar copyright.

**Comment by Walkman100** [comment]
@deavmi WELL? https://github.com/OpenStatus/OpenStatus-Client-Windows/issues/2#issuecomment-67640797

**Comment by deavmi** [comment]
Chat tomorrow.

**Comment by deavmi** [comment]
I am tired. And just came back from Cape Town.

**Comment by deavmi** [comment]
@Walkman100 Then please remove the `DeavmiOSS` part from them and anything associated to and around DeavmiOSS. Besdies creditation to me if I helped in any of the projects of yours.

**Comment by deavmi** [comment]
So we can close this issue, if you remove DeavmiOSS from this and all of your other projects.

**Comment by Walkman100** [comment]
The issue is the license, not the org association. that is for another issue, please see https://github.com/OpenStatus/OpenStatus-Client-Windows/issues/2#issuecomment-67640797

**Comment by deavmi** [comment]
Oh, well then must I change the license? @Walkman100

**Comment by deavmi** [comment]
Cause that is a dead simple task.

**Comment by Walkman100** [comment]
That is what I have been asking you to do since https://github.com/OpenStatus/OpenStatus-Client-Windows/issues/2#issuecomment-67640797

**Comment by Walkman100** [comment]
Reference this issue in the commit message, then it will be closed automatically

**Comment by deavmi** [comment]
Okay.

**Comment by deavmi** [comment]
Lol

**Comment by deavmi** [comment]
#FuckMIT lol
